version: '3.4'
services:

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - wordpress
    environment:
      BALANCE: leastconn
    ports:
      - 8000:80
    networks:
      - web
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 30s
      placement:
        constraints: [node.role == manager]
        
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DATABASE_HOST: mariadb-master
      WORDPRESS_DATABASE_NAME: mariadb-master
      WORDPRESS_DATABASE_USER: root
      WORDPRESS_DATABASE_PASSWORD: mariadbropass
      SERVICE_PORTS: 8080
      MARIADB_HOST: mariadb-master
      MARIADB_PORT_NUMBER: 3306
    depends_on:
      - mariadb-master
    networks:
      - web
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 30s
      
  mariadb-master:
    image: bitnami/mariadb:latest
    ports:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadbropass
      MARIADB_DATABASE: mariadb-master
      MARIADB_USER: mariadbuser
      MARIADB_PASSWORD: mariadbpass
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: mariadbrepuser
      MARIADB_REPLICATION_PASSWORD: mariadbreppass
    networks:
      - web
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 30s
      
     
  mariadb-slave:
    image: bitnami/mariadb:latest
    ports:
      - 3306
    environment:
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: mariadbrepuser
      MARIADB_REPLICATION_PASSWORD: mariadbreppass
      MARIADB_MASTER_HOST: mariadb-master
      MARIADB_MASTER_PORT_NUMBER: 3306
      MARIADB_MASTER_ROOT_PASSWORD: mariadbropass
    depends_on:
      - mariadb-master
    networks:
      - web
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: any
        delay: 30s

networks:
  web:
    driver: overlay
    