version: '3.4'
services:

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mariadb1
      WORDPRESS_DB_NAME: mariadb1
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mariadbropa
    depends_on:
      - mariadb1
    networks:
      - web
    restart: always
      
  mariadb1:
    image: mariadb:10.2
    container_name: mariadb1
    ports:
      - 8010:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadbropa
      MYSQL_DATABASE: mariadb1
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadbpa
    networks:
      - web
    restart: always
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

networks:
  web:
    driver: bridge         