version: '3.4'
services:

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mariadbropa
    depends_on:
      - mariadb
    networks:
      - web
    restart: always
      
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: mariadbropa
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadbpa
    networks:
      - web
    restart: always
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

networks:
  web:
    driver: bridge         